version: '3'
services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "adminPassword123!"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"